'use strict';
/**
 * fxmanifest.lua Reference Tests
 *
 * For every fxmanifest.lua in the resources tree, this test verifies that
 * each file referenced by a script / file / map / ui_page directive actually
 * exists on disk (relative to the manifest's own directory).
 *
 * Notes:
 *  • Build artefacts under dist/ are excluded — they require a webpack build
 *    step that cannot run in this environment.
 *  • Glob patterns (e.g. html/vendor/*.css) are resolved using Node's fs.glob
 *    (or a manual glob) and validated to match at least one existing file.
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

// ── Helpers ──────────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(__dirname, '..');
const RESOURCES_DIR = path.join(REPO_ROOT, 'resources');

/** Recursively find all fxmanifest.lua files. */
function findManifests(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...findManifests(full));
    else if (entry.isFile() && entry.name === 'fxmanifest.lua') results.push(full);
  }
  return results;
}

/**
 * Extract all explicitly listed file paths from an fxmanifest.lua source.
 *
 * Handles single-value directives:
 *   client_script 'path'
 *   server_script 'path'
 *   shared_script 'path'
 *   file          'path'
 *   map           'path'
 *   ui_page       'path'
 *   webpack_config 'path'
 *
 * And block directives:
 *   client_scripts { 'p1', 'p2' }
 *   server_scripts { ... }
 *   shared_scripts { ... }
 *   files          { ... }
 */
function extractFilePaths(source) {
  const paths = new Set();

  // Single-value directives: keyword 'path'  or  keyword "path"
  const singleRe = /(?:client_script|server_script|shared_script|file|map|ui_page|webpack_config)\s+['"]([^'"]+)['"]/g;
  for (const m of source.matchAll(singleRe)) paths.add(m[1]);

  // Block directives: keyword { 'path1', 'path2', ... }
  const blockRe = /(?:client_scripts|server_scripts|shared_scripts|files)\s*\{([^}]+)\}/gs;
  for (const block of source.matchAll(blockRe)) {
    const inner = block[1];
    const itemRe = /['"]([^'"]+)['"]/g;
    for (const item of inner.matchAll(itemRe)) paths.add(item[1]);
  }

  return [...paths];
}

/**
 * Return true if a path pattern contains glob metacharacters.
 */
function isGlob(p) {
  return /[*?[\]{}]/.test(p);
}

/**
 * Very small glob matcher supporting only * (within a segment) and **
 * (across segments).  Enough for the patterns found in cfx-server-data.
 */
function matchGlob(pattern, candidate) {
  // Convert glob pattern to a regex
  const escaped = pattern
    .replace(/\\/g, '/')
    .replace(/[.+^${}()|[\\\]]/g, '\\$&')  // escape regex specials (except * ?)
    .replace(/\*\*/g, '\u0001')             // placeholder for **
    .replace(/\*/g, '[^/]*')               // * → any chars except /
    .replace(/\?/g, '[^/]')                // ? → one char except /
    .replace(/\u0001/g, '.*');             // ** → any chars (inc. /)
  return new RegExp(`^${escaped}$`).test(candidate.replace(/\\/g, '/'));
}

/** Recursively list all files under dir as relative paths (forward-slash). */
function listAllFiles(dir, base = dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...listAllFiles(full, base));
    else results.push(path.relative(base, full).replace(/\\/g, '/'));
  }
  return results;
}

// ── Tests ────────────────────────────────────────────────────────────────────

const manifests = findManifests(RESOURCES_DIR);

describe('fxmanifest.lua file references', () => {
  assert.ok(manifests.length > 0, 'Should find at least one fxmanifest.lua');

  for (const manifestPath of manifests) {
    const label = path.relative(REPO_ROOT, manifestPath);
    const resourceDir = path.dirname(manifestPath);

    test(label, () => {
      const source = fs.readFileSync(manifestPath, 'utf8');
      const refs = extractFilePaths(source);

      for (const ref of refs) {
        // Skip build artefacts (dist/ directory) — these are generated by
        // webpack at runtime and are not committed to the repository.
        if (ref.startsWith('dist/')) continue;

        if (isGlob(ref)) {
          // For glob patterns, at least one matching file must exist.
          const allFiles = listAllFiles(resourceDir);
          const matches = allFiles.filter(f => matchGlob(ref, f));
          assert.ok(
            matches.length > 0,
            `Glob '${ref}' in ${label} matched no files in ${path.relative(REPO_ROOT, resourceDir)}`
          );
        } else {
          const full = path.join(resourceDir, ref);
          assert.ok(
            fs.existsSync(full),
            `Referenced file '${ref}' not found in ${path.relative(REPO_ROOT, resourceDir)} (${label})`
          );
        }
      }
    });
  }
});
